export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const FETCH_CALENDARS = 'FETCH_CALENDARS';
export const FETCH_CALENDARS_REQUEST = 'FETCH_CALENDARS_REQUEST';
export const FETCH_CALENDARS_SUCCESS = 'FETCH_CALENDARS_SUCCESS';
export const FETCH_CALENDARS_ERROR = 'FETCH_CALENDARS_ERROR';

export const FETCH_CALENDAR = 'FETCH_CALENDAR';
export const FETCH_CALENDAR_SUCCESS = 'FETCH_CALENDAR_SUCCESS';
export const FETCH_CALENDAR_ERROR = 'FETCH_CALENDAR_ERROR';

export const ADD_CALENDAR = 'ADD_CALENDAR';
export const ADD_CALENDAR_SUCCESS = 'ADD_CALENDAR_SUCCESS';
export const ADD_CALENDAR_ERROR = 'ADD_CALENDAR_ERROR';

export const EDIT_CALENDAR = 'EDIT_CALENDAR';
export const EDIT_CALENDAR_SUCCESS = 'EDIT_CALENDAR_SUCCESS';
export const EDIT_CALENDAR_ERROR = 'EDIT_CALENDAR_ERROR';



export const DELETE_CALENDAR = 'DELETE_CALENDAR';
export const DELETE_CALENDAR_SUCCESS = 'DELETE_CALENDAR_SUCCESS';
export const DELETE_CALENDAR_ERROR = 'DELETE_CALENDAR_ERROR';